# Generated by Django 4.0.6 on 2022-08-09 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description for your account", max_length=200
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Insert your account number here.", max_length=20
                    ),
                ),
                (
                    "balance",
                    models.FloatField(
                        default=0, help_text="Insert your initial balance."
                    ),
                ),
                (
                    "owner",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="Account Owner"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
