# Generated by Django 4.0.6 on 2022-08-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoqueapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "linha",
                    models.CharField(
                        help_text="Inserir linha a qual pertence o perfil.",
                        max_length=20,
                    ),
                ),
                (
                    "codigo_perfil",
                    models.CharField(
                        help_text="Código do perfil. ex: SU-001", max_length=200
                    ),
                ),
                (
                    "peso_kg_m",
                    models.FloatField(
                        default=0, help_text="Inserir peso por metro linear."
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        help_text="Descrição de uso do perfil. ex: TRILHO INFERIOR / 2 FOLHAS",
                        max_length=200,
                    ),
                ),
                (
                    "quantidade",
                    models.FloatField(
                        default=0,
                        help_text="Inserir quantidade em estoque - Favor insrir somente barras inteiras.",
                    ),
                ),
                (
                    "acabamento_cor",
                    models.FloatField(
                        default=0,
                        help_text="Inserir cor com Código. ex: BRANCO RAL9003",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Account",
        ),
    ]
