# Generated by Django 4.0.6 on 2022-08-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoqueapp', '0003_alter_perfil_acabamento_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='acabamento_cor',
            field=models.CharField(help_text='Inserir cor com Código. ex: BRANCO - RAL9003', max_length=40),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='descricao',
            field=models.CharField(help_text='Descrição de uso do perfil. ex: MARCO SUPERIOR / 2 FOLHAS.', max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='quantidade',
            field=models.IntegerField(default=0, help_text='Inserir quantidade em estoque - Favor insrir somente barras inteiras.'),
        ),
    ]
