# Generated by Django 4.0.6 on 2022-08-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoqueapp', '0004_alter_perfil_acabamento_cor_alter_perfil_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='peso_kg_m',
            field=models.FloatField(help_text='Inserir peso por metro linear.'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='quantidade',
            field=models.IntegerField(help_text='Inserir quantidade em estoque - Favor insrir somente barras inteiras.'),
        ),
    ]
