# Generated by Django 4.0.6 on 2022-08-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoqueapp', '0005_alter_perfil_peso_kg_m_alter_perfil_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='acabamento_cor',
            field=models.CharField(help_text='Inserir cor com Código. ex: BRANCO-RAL9003', max_length=40),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='quantidade',
            field=models.IntegerField(help_text='Inserir quantidade em estoque - Favor inserir somente barras inteiras.'),
        ),
    ]
